filebeat.modules:

tags: ${FB_TAGS:filebeat}

filebeat.prospectors:

- input_type: log
  paths: 
  - "/usr/local/log/1/*.log"
  - "/usr/local/log/1/*/*.log"
  - "/usr/local/log/2/*.log"
  - "/usr/local/log/2/*/*.log"
  - "/usr/local/log/3/*.log"
  - "/usr/local/log/3/*/*.log"
  - "/usr/local/log/4/*.log"
  - "/usr/local/log/4/*/*.log"
  - "/usr/local/log/5/*.log"
  - "/usr/local/log/5/*/*.log"
  - "/usr/local/log/6/*.log"
  - "/usr/local/log/6/*/*.log"
  - "/usr/local/log/7/*.log"
  - "/usr/local/log/7/*/*.log"
  - "/usr/local/log/8/*.log"
  - "/usr/local/log/8/*/*.log"
  - "/usr/local/log/9/*.log"
  - "/usr/local/log/9/*/*.log"
  - "/usr/local/log/10/*.log"
  - "/usr/local/log/10/*/*.log"

  ignore_older: "12h"
  clean_inactive: "72h"
  exclude_lines: ['^DEBUG']

  multiline.pattern: '^[[:space:]]+|^Caused by:|^---[[:space:]]|^$'
  multiline.negate: false
  multiline.match: after

output.logstash:
  hosts: ["logstash:5043"]
  ssl.certificate_authorities: ["/mnt/ca/ca.cert"]
  ssl.certificate: "/mnt/cert/client.cert"
  ssl.key: "/mnt/cert/client.key"
  ssl.enabled: ${LOGSTASH_SSL_ENABLED}
  ssl.verification_mode: none

path.data: /data

logging.level: ${FB_LOG_LEVEL:info}
logging.to_files: false
logging.to_syslog: true