version: "2"

services:

  logspout:
    image: gliderlabs/logspout
    environment:
      - DEBUG=true
      - LOGSPOUT=ignore
      - BACKLOG=false
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    extends:
      service: logging

  filebeat:
    volumes:
    - ${LOG_PATH}:/usr/local/log/1
    - ${LOG2_PATH}:/usr/local/log/2
    - ${LOG3_PATH}:/usr/local/log/3
    - ${LOG4_PATH}:/usr/local/log/4
    - ${LOG5_PATH}:/usr/local/log/5
    - ${LOG6_PATH}:/usr/local/log/6
    - ${LOG7_PATH}:/usr/local/log/7
    - ${LOG8_PATH}:/usr/local/log/8
    - ${LOG9_PATH}:/usr/local/log/9
    - ${LOG10_PATH}:/usr/local/log/10
    - ${FB_DATA_HOME}:/data
    environment: 
    - LOGSPOUT=ignore
    - FB_TAGS
    - FB_LOG_LEVEL
    extends:
      service: logging

  cadvisor:
    image: google/cadvisor:latest
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    environment: 
      - LOGSPOUT=ignore
    extends:
      service: logging

  logging:
    logging: 
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"