version: "2"

services:

  logspout:
    volumes:
    - ${CA_CERTIFICATE}:/mnt/ca/ca.cert:ro
    - ${CLIENT_CERTIFICATE}:/mnt/cert/client.cert:ro
    - ${CLIENT_KEY}:/mnt/cert/client.key:ro
    command: syslog+tls://${LOGSTASH_URL}:5000

  filebeat:
    volumes:
    - ${CA_CERTIFICATE}:/mnt/ca/ca.cert:ro
    - ${CLIENT_CERTIFICATE}:/mnt/cert/client.cert:ro
    - ${CLIENT_KEY}:/mnt/cert/client.key:ro
    environment:
    - LOGSTASH_SSL_ENABLED=True